// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: server/chain.proto

package server

import (

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassId string `protobuf:"bytes,1,opt,name=ClassId,proto3" json:"ClassId,omitempty"`
	Uri     string `protobuf:"bytes,2,opt,name=Uri,proto3" json:"Uri,omitempty"`
	UriHash string `protobuf:"bytes,3,opt,name=UriHash,proto3" json:"UriHash,omitempty"`
}

func (x *CreateNftRequest) Reset() {
	*x = CreateNftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNftRequest) ProtoMessage() {}

func (x *CreateNftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_chain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNftRequest.ProtoReflect.Descriptor instead.
func (*CreateNftRequest) Descriptor() ([]byte, []int) {
	return file_server_chain_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNftRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *CreateNftRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CreateNftRequest) GetUriHash() string {
	if x != nil {
		return x.UriHash
	}
	return ""
}

type CreateNftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CreateNftResponse) Reset() {
	*x = CreateNftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNftResponse) ProtoMessage() {}

func (x *CreateNftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_chain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNftResponse.ProtoReflect.Descriptor instead.
func (*CreateNftResponse) Descriptor() ([]byte, []int) {
	return file_server_chain_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNftResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ClassByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TxHash string `protobuf:"bytes,2,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Owner  string `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Id     string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClassByIDRequest) Reset() {
	*x = ClassByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassByIDRequest) ProtoMessage() {}

func (x *ClassByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_chain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassByIDRequest.ProtoReflect.Descriptor instead.
func (*ClassByIDRequest) Descriptor() ([]byte, []int) {
	return file_server_chain_proto_rawDescGZIP(), []int{2}
}

func (x *ClassByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassByIDRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ClassByIDRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ClassByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClassByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Uri  string `protobuf:"bytes,3,opt,name=Uri,proto3" json:"Uri,omitempty"`
}

func (x *ClassByIDResponse) Reset() {
	*x = ClassByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassByIDResponse) ProtoMessage() {}

func (x *ClassByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_chain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassByIDResponse.ProtoReflect.Descriptor instead.
func (*ClassByIDResponse) Descriptor() ([]byte, []int) {
	return file_server_chain_proto_rawDescGZIP(), []int{3}
}

func (x *ClassByIDResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ClassByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassByIDResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_server_chain_proto protoreflect.FileDescriptor

var file_server_chain_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x58, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x69,
	0x12, 0x18, 0x0a, 0x07, 0x55, 0x72, 0x69, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x55, 0x72, 0x69, 0x48, 0x61, 0x73, 0x68, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x78, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x72, 0x69, 0x32, 0xe5, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x66, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x6a, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x66, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x22, 0x0c, 0x2f, 0x6e, 0x66, 0x74, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73,
	0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x12, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x6e, 0x66, 0x74, 0x2f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x1a, 0x5a, 0x18,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_chain_proto_rawDescOnce sync.Once
	file_server_chain_proto_rawDescData = file_server_chain_proto_rawDesc
)

func file_server_chain_proto_rawDescGZIP() []byte {
	file_server_chain_proto_rawDescOnce.Do(func() {
		file_server_chain_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_chain_proto_rawDescData)
	})
	return file_server_chain_proto_rawDescData
}

var file_server_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_chain_proto_goTypes = []interface{}{
	(*CreateNftRequest)(nil),  // 0: chainservice.CreateNftRequest
	(*CreateNftResponse)(nil), // 1: chainservice.CreateNftResponse
	(*ClassByIDRequest)(nil),  // 2: chainservice.ClassByIDRequest
	(*ClassByIDResponse)(nil), // 3: chainservice.ClassByIDResponse
}
var file_server_chain_proto_depIdxs = []int32{
	0, // 0: chainservice.CreateNftClass.CreateNftClass:input_type -> chainservice.CreateNftRequest
	2, // 1: chainservice.CreateNftClass.ClassByID:input_type -> chainservice.ClassByIDRequest
	1, // 2: chainservice.CreateNftClass.CreateNftClass:output_type -> chainservice.CreateNftResponse
	3, // 3: chainservice.CreateNftClass.ClassByID:output_type -> chainservice.ClassByIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_chain_proto_init() }
func file_server_chain_proto_init() {
	if File_server_chain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_chain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_chain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_chain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_chain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_chain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_chain_proto_goTypes,
		DependencyIndexes: file_server_chain_proto_depIdxs,
		MessageInfos:      file_server_chain_proto_msgTypes,
	}.Build()
	File_server_chain_proto = out.File
	file_server_chain_proto_rawDesc = nil
	file_server_chain_proto_goTypes = nil
	file_server_chain_proto_depIdxs = nil
}
