// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: server/wenchangnative.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreateNftClassClient is the client API for CreateNftClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateNftClassClient interface {
	CreateNftClass(ctx context.Context, in *CreateNftRequest, opts ...grpc.CallOption) (*CreateNftResponse, error)
	ClassByID(ctx context.Context, in *ClassByIDRequest, opts ...grpc.CallOption) (*ClassByIDResponse, error)
}

type createNftClassClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateNftClassClient(cc grpc.ClientConnInterface) CreateNftClassClient {
	return &createNftClassClient{cc}
}

func (c *createNftClassClient) CreateNftClass(ctx context.Context, in *CreateNftRequest, opts ...grpc.CallOption) (*CreateNftResponse, error) {
	out := new(CreateNftResponse)
	err := c.cc.Invoke(ctx, "/chainservice.CreateNftClass/CreateNftClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createNftClassClient) ClassByID(ctx context.Context, in *ClassByIDRequest, opts ...grpc.CallOption) (*ClassByIDResponse, error) {
	out := new(ClassByIDResponse)
	err := c.cc.Invoke(ctx, "/chainservice.CreateNftClass/ClassByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateNftClassServer is the server API for CreateNftClass service.
// All implementations must embed UnimplementedCreateNftClassServer
// for forward compatibility
type CreateNftClassServer interface {
	CreateNftClass(context.Context, *CreateNftRequest) (*CreateNftResponse, error)
	ClassByID(context.Context, *ClassByIDRequest) (*ClassByIDResponse, error)
	mustEmbedUnimplementedCreateNftClassServer()
}

// UnimplementedCreateNftClassServer must be embedded to have forward compatible implementations.
type UnimplementedCreateNftClassServer struct {
}

func (UnimplementedCreateNftClassServer) CreateNftClass(context.Context, *CreateNftRequest) (*CreateNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNftClass not implemented")
}
func (UnimplementedCreateNftClassServer) ClassByID(context.Context, *ClassByIDRequest) (*ClassByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassByID not implemented")
}
func (UnimplementedCreateNftClassServer) mustEmbedUnimplementedCreateNftClassServer() {}

// UnsafeCreateNftClassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateNftClassServer will
// result in compilation errors.
type UnsafeCreateNftClassServer interface {
	mustEmbedUnimplementedCreateNftClassServer()
}

func RegisterCreateNftClassServer(s grpc.ServiceRegistrar, srv CreateNftClassServer) {
	s.RegisterService(&CreateNftClass_ServiceDesc, srv)
}

func _CreateNftClass_CreateNftClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateNftClassServer).CreateNftClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainservice.CreateNftClass/CreateNftClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateNftClassServer).CreateNftClass(ctx, req.(*CreateNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreateNftClass_ClassByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateNftClassServer).ClassByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainservice.CreateNftClass/ClassByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateNftClassServer).ClassByID(ctx, req.(*ClassByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateNftClass_ServiceDesc is the grpc.ServiceDesc for CreateNftClass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateNftClass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainservice.CreateNftClass",
	HandlerType: (*CreateNftClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNftClass",
			Handler:    _CreateNftClass_CreateNftClass_Handler,
		},
		{
			MethodName: "ClassByID",
			Handler:    _CreateNftClass_ClassByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/wenchangnative.proto",
}
